<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_673db0fb7c0f8',
    'title' => __('Appearance - Alingsås', 'municipio-customisation'),
    'fields' => array(
        0 => array(
            'key' => 'field_673db0fb1b912',
            'label' => __('Colors', 'municipio-customisation'),
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        1 => array(
            'key' => 'field_673db188c0196',
            'label' => __('Custom colors', 'municipio-customisation'),
            'name' => 'alingsas_custom_colors',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'acfe_repeater_stylised_button' => 0,
            'layout' => 'block',
            'pagination' => 0,
            'min' => 0,
            'max' => 0,
            'collapsed' => 'field_673db1c1c0197',
            'button_label' => __('Add color', 'municipio-customisation'),
            'rows_per_page' => 20,
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_673dc384fb40f',
                    'label' => __('ID', 'municipio-customisation'),
                    'name' => 'id',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_673db188c0196',
                ),
                1 => array(
                    'key' => 'field_673db1c1c0197',
                    'label' => __('Name', 'municipio-customisation'),
                    'name' => 'name',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_673db188c0196',
                ),
                2 => array(
                    'key' => 'field_673db1e1c0198',
                    'label' => __('Color', 'municipio-customisation'),
                    'name' => 'color',
                    'aria-label' => '',
                    'type' => 'color_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'enable_opacity' => 0,
                    'return_format' => 'string',
                    'parent_repeater' => 'field_673db188c0196',
                ),
            ),
        ),
        2 => array(
            'key' => 'field_673db173c0195',
            'label' => __('Themes', 'municipio-customisation'),
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        3 => array(
            'key' => 'field_673db58fbaeef',
            'label' => __('Themes', 'municipio-customisation'),
            'name' => 'alingsas_themes',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'acfe_repeater_stylised_button' => 0,
            'layout' => 'block',
            'pagination' => 0,
            'min' => 0,
            'max' => 0,
            'collapsed' => 'field_673dc12fa4c63',
            'button_label' => __('Add theme', 'municipio-customisation'),
            'rows_per_page' => 20,
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_673f13830a0c2',
                    'label' => __('ID', 'municipio-customisation'),
                    'name' => 'id',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_673db58fbaeef',
                ),
                1 => array(
                    'key' => 'field_673dc12fa4c63',
                    'label' => __('Name', 'municipio-customisation'),
                    'name' => 'name',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_673db58fbaeef',
                ),
                2 => array(
                    'key' => 'field_673db6b8e0e37',
                    'label' => __('Theme color', 'municipio-customisation'),
                    'name' => 'theme_color',
                    'aria-label' => '',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                    ),
                    'default_value' => false,
                    'return_format' => 'value',
                    'multiple' => 0,
                    'allow_null' => 0,
                    'ui' => 0,
                    'ajax' => 0,
                    'placeholder' => '',
                    'allow_custom' => 0,
                    'search_placeholder' => '',
                    'parent_repeater' => 'field_673db58fbaeef',
                ),
                3 => array(
                    'key' => 'field_673f789c33066',
                    'label' => __('Buttons', 'municipio-customisation'),
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                    'parent_repeater' => 'field_673db58fbaeef',
                ),
                4 => array(
                    'key' => 'field_673f7430f642d',
                    'label' => __('Card', 'municipio-customisation'),
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                    'parent_repeater' => 'field_673db58fbaeef',
                ),
                5 => array(
                    'key' => 'field_673f73fbf642c',
                    'label' => __('Sidebar', 'municipio-customisation'),
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                    'parent_repeater' => 'field_673db58fbaeef',
                ),
                6 => array(
                    'key' => 'field_673f756d42373',
                    'label' => __('Background', 'municipio-customisation'),
                    'name' => 'var_sidebar_background',
                    'aria-label' => '',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'acfe_seamless_style' => 0,
                    'acfe_group_modal' => 0,
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_673f75ad42374',
                            'label' => __('Color', 'municipio-customisation'),
                            'name' => 'alingsas_color',
                            'aria-label' => '',
                            'type' => 'select',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                            ),
                            'default_value' => false,
                            'return_format' => 'value',
                            'multiple' => 0,
                            'allow_null' => 0,
                            'ui' => 0,
                            'ajax' => 0,
                            'placeholder' => '',
                            'allow_custom' => 0,
                            'search_placeholder' => '',
                        ),
                        1 => array(
                            'key' => 'field_673f75c442375',
                            'label' => __('Custom color', 'municipio-customisation'),
                            'name' => 'alingsas_custom_color',
                            'aria-label' => '',
                            'type' => 'color_picker',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_673f75ad42374',
                                        'operator' => '==contains',
                                        'value' => 'custom',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'enable_opacity' => 0,
                            'return_format' => 'string',
                        ),
                    ),
                    'acfe_group_modal_close' => 0,
                    'acfe_group_modal_button' => '',
                    'acfe_group_modal_size' => 'large',
                    'parent_repeater' => 'field_673db58fbaeef',
                ),
                7 => array(
                    'key' => 'field_673f760042376',
                    'label' => __('Text', 'municipio-customisation'),
                    'name' => 'var_sidebar_color',
                    'aria-label' => '',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'acfe_seamless_style' => 0,
                    'acfe_group_modal' => 0,
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_673f760042377',
                            'label' => __('Color', 'municipio-customisation'),
                            'name' => 'alingsas_color',
                            'aria-label' => '',
                            'type' => 'select',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                            ),
                            'default_value' => false,
                            'return_format' => 'value',
                            'multiple' => 0,
                            'allow_null' => 0,
                            'ui' => 0,
                            'ajax' => 0,
                            'placeholder' => '',
                            'allow_custom' => 0,
                            'search_placeholder' => '',
                        ),
                        1 => array(
                            'key' => 'field_673f760042378',
                            'label' => __('Custom color', 'municipio-customisation'),
                            'name' => 'alingsas_custom_color',
                            'aria-label' => '',
                            'type' => 'color_picker',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_673f760042377',
                                        'operator' => '==contains',
                                        'value' => 'custom',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'enable_opacity' => 0,
                            'return_format' => 'string',
                        ),
                    ),
                    'acfe_group_modal_close' => 0,
                    'acfe_group_modal_button' => '',
                    'acfe_group_modal_size' => 'large',
                    'parent_repeater' => 'field_673db58fbaeef',
                ),
            ),
        ),
        4 => array(
            'key' => 'field_673f826624f3f',
            'label' => __('Themes by route', 'municipio-customisation'),
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'acf-options-alingsas',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'left',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'acfe_display_title' => '',
    'acfe_autosync' => array(
        0 => 'json',
    ),
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
));
}