<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_6751b8151858a',
    'title' => __('Alingsås klonfält', 'municipio-customisation'),
    'fields' => array(
        0 => array(
            'key' => 'field_6751b8156d755',
            'label' => __('Color settings', 'municipio-customisation'),
            'name' => 'color_settings',
            'aria-label' => '',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'acfe_seamless_style' => 0,
            'acfe_group_modal' => 0,
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_6751b8d16d756',
                    'label' => __('Background', 'municipio-customisation'),
                    'name' => 'background',
                    'aria-label' => '',
                    'type' => 'clone',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'clone' => array(
                        0 => 'field_6751b92a6d758',
                        1 => 'field_6751b9566d759',
                    ),
                    'display' => 'group',
                    'layout' => 'block',
                    'prefix_label' => 0,
                    'prefix_name' => 1,
                    'acfe_seamless_style' => 1,
                    'acfe_clone_modal' => 0,
                    'acfe_clone_modal_close' => 0,
                    'acfe_clone_modal_button' => '',
                    'acfe_clone_modal_size' => 'large',
                ),
                1 => array(
                    'key' => 'field_6751b91d6d757',
                    'label' => __('Text', 'municipio-customisation'),
                    'name' => 'color',
                    'aria-label' => '',
                    'type' => 'clone',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'clone' => array(
                        0 => 'field_6751b92a6d758',
                        1 => 'field_6751b9566d759',
                    ),
                    'display' => 'group',
                    'layout' => 'block',
                    'prefix_label' => 0,
                    'prefix_name' => 1,
                    'acfe_seamless_style' => 1,
                    'acfe_clone_modal' => 0,
                    'acfe_clone_modal_close' => 0,
                    'acfe_clone_modal_button' => '',
                    'acfe_clone_modal_size' => 'large',
                ),
            ),
            'acfe_group_modal_close' => 0,
            'acfe_group_modal_button' => '',
            'acfe_group_modal_size' => 'large',
        ),
        1 => array(
            'key' => 'field_6751b92a6d758',
            'label' => __('Color', 'municipio-customisation'),
            'name' => 'alingsas_color',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
            ),
            'default_value' => false,
            'return_format' => 'value',
            'multiple' => 0,
            'allow_custom' => 0,
            'placeholder' => '',
            'search_placeholder' => '',
            'allow_null' => 0,
            'ui' => 0,
            'ajax' => 0,
        ),
        2 => array(
            'key' => 'field_6751b9566d759',
            'label' => __('Custom color', 'municipio-customisation'),
            'name' => 'alingsas_custom_color',
            'aria-label' => '',
            'type' => 'color_picker',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_6751b92a6d758',
                        'operator' => '==contains',
                        'value' => 'custom',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'enable_opacity' => 0,
            'return_format' => 'string',
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'post',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'left',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'acfe_display_title' => '',
    'acfe_autosync' => array(
        0 => 'json',
    ),
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
));
}